Update pipeline recipe-api-cicd

diff --git a/.harness/orgs/default/projects/default_project/pipelines/publishhelmchart.yaml b/.harness/orgs/default/projects/default_project/pipelines/publishhelmchart.yaml
--- a/.harness/orgs/default/projects/default_project/pipelines/publishhelmchart.yaml
+++ b/.harness/orgs/default/projects/default_project/pipelines/publishhelmchart.yaml
@@ -9,7 +9,10 @@ pipeline:
       codebase:
         connectorRef: pwgh1
         repoName: recipe-api
-        build: <+input>
+        build:
+          type: branch
+          spec:
+            branch: main
   stages:
     - stage:
         name: build-test-publish-image
@@ -44,10 +47,10 @@ pipeline:
                       dotnet format --verify-no-changes || echo "Linting failed or not configured, passing for now to avoid build break if not set up"
 
                       echo "Running Tests"
-                      dotnet test || echo "No tests found or test failed, ignoring for now"
+                      dotnet test --no-restore || echo "No tests found or test failed, ignoring for now"
 
                       echo "Building Project"
-                      dotnet build
+                      dotnet build --no-restore -c Release
               - step:
                   type: BuildAndPushDockerRegistry
                   name: BuildAndPushDockerRegistry_1
